// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders.get').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout.post').default>>>>
    }
    '/api/exchange-rates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exchange-rates.get').default>>>>
    }
    '/api/livreur/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/livreur/orders.get').default>>>>
    }
    '/api/livreur/orders/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/livreur/orders/[id].patch').default>>>>
    }
    '/api/paystack-webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/paystack-webhook.post').default>>>>
    }
    '/api/verify-payment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/verify-payment.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}